### ISSUE TITLE
cannot disable notification when app is closed

### ISSUE THREAD

**Issue by awukuernest483** [draxdave/netWatch#1]

**Comment by thesiamak** [comment]
OK let me see. 

Working on it..

**Comment by thesiamak** [comment]
@awukuernest483 
I couldn't understand what exactly the problem is.

if you set :
`.setNotificationCancelable(false)`
 then hiding notification is permitted until the app gets closed (Notification will be gone automatically).

please explain more detailed: OS ver , Device info ,
